// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwhqiddmkziladwfeggn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3aHFpZGRta3ppbGFkd2ZlZ2duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTk4OTQsImV4cCI6MjA2NjM3NTg5NH0.9f_5sJTA5u8H-tbTvsUiHBMhu9egkyupqaeQ-dOSGSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Enable automatic session refresh
    autoRefreshToken: true,
    // Persist session in localStorage
    persistSession: true,
    // Detect session in URL
    detectSessionInUrl: true,
    // Flow type for authentication
    flowType: 'pkce',
  },
  // Global headers
  global: {
    headers: {
      'X-Client-Info': 'food-prep-manager-web',
    },
  },
});